name: Build miyadaiku

on: 
  push:
  schedule:
    - cron:  '5 */12 * * *'

jobs:
  build:
    name: build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache download dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-pip2-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create venv
        run: |
          python3 -m venv .venv

      - name: Cache venv dependencies
        uses: actions/cache@v1
        with:
          path: .venv
          key: ${{ runner.os }}-venv2-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv2-

      - name: Install dependencies
        run: |
          .venv/bin/pip3 install -r requirements.txt

      - name: build miyadaiku
        run: |
          .venv/bin/miyadaiku-build .

      - name: push changes
        run: |
          mv outputs/README.md .
          git config --global user.name 'github actions'
          git config --global user.email 'atsuoishimoto@users.noreply.github.com'
          git add README.md || true
          git commit -m "updated" || true
          git push || true
